sonar.projectKey=chrysa_diy-stream-deck
sonar.organization=chrysa
sonar.projectName=diy-stream-deck
sonar.sources=diy_stream_deck
sonar.tests=tests
sonar.python.version=3.14
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/.mypy_cache/**
sonar.coverage.exclusions=tests/**
