on:
  pull_request: null
jobs:
  dependencies:
    name: Check PR dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: gregsdennis/dependencies-action@a8cccab69814b9b985496cf97cbfe154c96c03c7 # v1.4.2
name: Dependencies